---
- name: Scan targets
  hosts: scanners
  become: true

  tasks:
    - name: Install NMAP
      ansible.builtin.apt:
        name: nmap
        state: present
        update_cache: true

    - name: Scan
      ansible.builtin.command: "nmap {{ item }} -p 80 -oG -"
      loop: "{{ lookup('file', './targets.txt').splitlines() }}"
      register: scan_results

    - name: Show scan results
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ scan_results.results }}"
