---
- name: Scan targets
  hosts: scanners
  become: true
  become_method: sudo

  tasks:
  - name: Ensure NMAP installed
    ansible.builtin.apt:
      name: nmap
      state: present

  - name: Copy nmap targets list
    copy:
        src: ./targets.txt
        dest: ~/targets.txt
        force: yes
        mode: 0644

  - name: Run nmap
    shell: "nmap -iL ~/targets.txt -p 80 -oG -"
    register: nmap_result

  - name: Nmap output
    debug:
      msg: "{{ nmap_result.stdout_lines }}"